"""
PowerPoint Generator for Creating Presentations
Adapted from SlideBron with cybersecurity theme.
"""
import logging
from datetime import datetime
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import os

logger = logging.getLogger(__name__)


class PPTXGenerator:
    """Generator for creating PowerPoint presentations."""
    
    # Theme configurations
    THEMES = {
        "professional": {
            "bg_color": RGBColor(255, 255, 255),
            "title_color": RGBColor(31, 78, 121),
            "text_color": RGBColor(64, 64, 64),
            "accent_color": RGBColor(0, 112, 192)
        },
        "modern": {
            "bg_color": RGBColor(248, 248, 248),
            "title_color": RGBColor(68, 68, 68),
            "text_color": RGBColor(102, 102, 102),
            "accent_color": RGBColor(0, 188, 212)
        },
        "minimal": {
            "bg_color": RGBColor(255, 255, 255),
            "title_color": RGBColor(33, 33, 33),
            "text_color": RGBColor(66, 66, 66),
            "accent_color": RGBColor(100, 100, 100)
        },
        "dark": {
            "bg_color": RGBColor(30, 30, 30),
            "title_color": RGBColor(0, 255, 136),
            "text_color": RGBColor(220, 220, 220),
            "accent_color": RGBColor(0, 200, 100)
        }
    }
    
    def __init__(self, theme: str = "professional"):
        """
        Initialize the PPTX generator.
        
        Args:
            theme: Theme name (professional, modern, minimal, dark)
        """
        self.theme_name = theme
        self.theme = self.THEMES.get(theme, self.THEMES["professional"])
        logger.info(f"PPTXGenerator initialized with theme: {theme}")
    
    def create_presentation(
        self,
        title: str,
        slides_content: list,
        output_path: str
    ) -> str:
        """
        Create a PowerPoint presentation.
        
        Args:
            title: Presentation title
            slides_content: List of slide dictionaries with 'title' and 'content'
            output_path: Path to save the presentation
            
        Returns:
            Path to the generated file
        """
        try:
            prs = Presentation()
            prs.slide_width = Inches(10)
            prs.slide_height = Inches(7.5)
            
            # Add title slide
            self._add_title_slide(prs, title)
            
            # Add content slides
            for slide_data in slides_content:
                self._add_content_slide(
                    prs,
                    slide_data.get("title", ""),
                    slide_data.get("content", [])
                )
            
            # Add closing slide
            self._add_closing_slide(prs, title)
            
            # Save presentation
            prs.save(output_path)
            logger.info(f"Presentation saved to: {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"Error creating presentation: {e}")
            raise
    
    def _add_title_slide(self, prs, title: str):
        """Add title slide to presentation."""
        slide_layout = prs.slide_layouts[6]  # Blank layout
        slide = prs.slides.add_slide(slide_layout)
        
        # Set background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = self.theme["bg_color"]
        
        # Add title
        left = Inches(1)
        top = Inches(2.5)
        width = Inches(8)
        height = Inches(2)
        
        title_box = slide.shapes.add_textbox(left, top, width, height)
        title_frame = title_box.text_frame
        title_frame.text = title
        
        p = title_frame.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        p.font.size = Pt(44)
        p.font.bold = True
        p.font.color.rgb = self.theme["title_color"]
        
        # Add subtitle
        subtitle_box = slide.shapes.add_textbox(Inches(1), Inches(5), Inches(8), Inches(1))
        subtitle_frame = subtitle_box.text_frame
        subtitle_frame.text = f"Generated by CyberBron | {datetime.now().strftime('%Y-%m-%d')}"
        
        p = subtitle_frame.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        p.font.size = Pt(18)
        p.font.color.rgb = self.theme["text_color"]
    
    def _add_content_slide(self, prs, title: str, content):
        """Add content slide to presentation."""
        slide_layout = prs.slide_layouts[6]  # Blank layout
        slide = prs.slides.add_slide(slide_layout)
        
        # Set background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = self.theme["bg_color"]
        
        # Add title
        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(9), Inches(1))
        title_frame = title_box.text_frame
        title_frame.text = title
        
        p = title_frame.paragraphs[0]
        p.font.size = Pt(32)
        p.font.bold = True
        p.font.color.rgb = self.theme["title_color"]
        
        # Add content - handle both paragraph strings and lists
        content_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.8), Inches(9), Inches(5))
        content_frame = content_box.text_frame
        content_frame.word_wrap = True
        
        if isinstance(content, str):
            # Full paragraph content
            content_frame.text = content
            p = content_frame.paragraphs[0]
            p.font.size = Pt(16)
            p.font.color.rgb = self.theme["text_color"]
            p.line_spacing = 1.5
            p.space_after = Pt(12)
        elif isinstance(content, list):
            # Legacy bullet point support
            for item in content:
                p = content_frame.add_paragraph()
                p.text = f"• {item}"
                p.font.size = Pt(18)
                p.font.color.rgb = self.theme["text_color"]
                p.space_after = Pt(12)
    
    def _add_closing_slide(self, prs, title: str):
        """Add closing slide to presentation."""
        slide_layout = prs.slide_layouts[6]
        slide = prs.slides.add_slide(slide_layout)
        
        # Set background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = self.theme["bg_color"]
        
        # Add closing message
        text_box = slide.shapes.add_textbox(Inches(1), Inches(3), Inches(8), Inches(2))
        text_frame = text_box.text_frame
        text_frame.text = "Thank You!"
        
        p = text_frame.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        p.font.size = Pt(44)
        p.font.bold = True
        p.font.color.rgb = self.theme["title_color"]
        
        # Add footer
        footer_box = slide.shapes.add_textbox(Inches(1), Inches(6), Inches(8), Inches(1))
        footer_frame = footer_box.text_frame
        footer_frame.text = f"Powered by CyberBron"
        
        p = footer_frame.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        p.font.size = Pt(18)
        p.font.color.rgb = self.theme["text_color"]
